-- MySQL Script generated by MySQL Workbench
-- Fri Jun 28 14:37:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe` ;

CREATE TABLE IF NOT EXISTS `Classe` (
  `ID_Classe` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID_Classe`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_Classe_UNIQUE` ON `Classe` (`ID_Classe` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Habilidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Habilidade` ;

CREATE TABLE IF NOT EXISTS `Habilidade` (
  `ID_Habilidade` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Descricao` VARCHAR(200) NULL,
  `Trilha_ID_Trilha` INT NOT NULL,
  `Origem_ID_Origem` INT NOT NULL,
  PRIMARY KEY (`ID_Habilidade`, `Trilha_ID_Trilha`, `Origem_ID_Origem`),
  CONSTRAINT `fk_Habilidade_Trilha1`
    FOREIGN KEY (`Trilha_ID_Trilha`)
    REFERENCES `Trilha` (`ID_Trilha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habilidade_Origem1`
    FOREIGN KEY (`Origem_ID_Origem`)
    REFERENCES `Origem` (`ID_Origem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Habilidade_Trilha1_idx` ON `Habilidade` (`Trilha_ID_Trilha` ASC) VISIBLE;

CREATE INDEX `fk_Habilidade_Origem1_idx` ON `Habilidade` (`Origem_ID_Origem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jogador` ;

CREATE TABLE IF NOT EXISTS `Jogador` (
  `ID_Jogador` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Gênero` CHAR(1) NOT NULL,
  PRIMARY KEY (`ID_Jogador`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_Jogador_UNIQUE` ON `Jogador` (`ID_Jogador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Origem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Origem` ;

CREATE TABLE IF NOT EXISTS `Origem` (
  `ID_Origem` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID_Origem`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_Origem_UNIQUE` ON `Origem` (`ID_Origem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Personagem` ;

CREATE TABLE IF NOT EXISTS `Personagem` (
  `ID_Personagem` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Gênero` CHAR(1) NOT NULL,
  `Pontos de Vida` INT NOT NULL,
  `Pontos de Sanidade` INT NOT NULL,
  `Pontos de Esforço` INT NOT NULL,
  `NEX` INT NOT NULL,
  `Jogador_ID_Jogador` INT NOT NULL,
  `Classe_ID_Classe` INT NOT NULL,
  `Origem_ID_Origem` INT NOT NULL,
  PRIMARY KEY (`ID_Personagem`, `Jogador_ID_Jogador`, `Classe_ID_Classe`, `Origem_ID_Origem`),
  CONSTRAINT `fk_Personagem_Jogador`
    FOREIGN KEY (`Jogador_ID_Jogador`)
    REFERENCES `Jogador` (`ID_Jogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personagem_Classe1`
    FOREIGN KEY (`Classe_ID_Classe`)
    REFERENCES `Classe` (`ID_Classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personagem_Origem1`
    FOREIGN KEY (`Origem_ID_Origem`)
    REFERENCES `Origem` (`ID_Origem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_Personagem_UNIQUE` ON `Personagem` (`ID_Personagem` ASC) VISIBLE;

CREATE INDEX `fk_Personagem_Jogador_idx` ON `Personagem` (`Jogador_ID_Jogador` ASC) VISIBLE;

CREATE INDEX `fk_Personagem_Classe1_idx` ON `Personagem` (`Classe_ID_Classe` ASC) VISIBLE;

CREATE INDEX `fk_Personagem_Origem1_idx` ON `Personagem` (`Origem_ID_Origem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Perícia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Perícia` ;

CREATE TABLE IF NOT EXISTS `Perícia` (
  `ID_Pericia` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(200) NOT NULL,
  `Origem_ID_Origem` INT NOT NULL,
  PRIMARY KEY (`ID_Pericia`, `Origem_ID_Origem`),
  CONSTRAINT `fk_Perícia_Origem1`
    FOREIGN KEY (`Origem_ID_Origem`)
    REFERENCES `Origem` (`ID_Origem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_Pericia_UNIQUE` ON `Perícia` (`ID_Pericia` ASC) VISIBLE;

CREATE INDEX `fk_Perícia_Origem1_idx` ON `Perícia` (`Origem_ID_Origem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Trilha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trilha` ;

CREATE TABLE IF NOT EXISTS `Trilha` (
  `ID_Trilha` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(200) NOT NULL,
  `Classe_ID_Classe` INT NOT NULL,
  PRIMARY KEY (`ID_Trilha`, `Classe_ID_Classe`),
  CONSTRAINT `fk_Trilha_Classe1`
    FOREIGN KEY (`Classe_ID_Classe`)
    REFERENCES `Classe` (`ID_Classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Trilha_Classe1_idx` ON `Trilha` (`Classe_ID_Classe` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
