-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 19:46:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PUCMinas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PUCMinas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PUCMinas` DEFAULT CHARACTER SET utf8 ;
USE `PUCMinas` ;

-- -----------------------------------------------------
-- Table `PUCMinas`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUCMinas`.`Area` (
  `Sigla` VARCHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `SuperArea` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Area_Area1_idx` (`SuperArea` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Area1`
    FOREIGN KEY (`SuperArea`)
    REFERENCES `PUCMinas`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PUCMinas`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUCMinas`.`Curso` (
  `Sigla` VARCHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Horas` INT UNSIGNED NULL,
  `Custo` DOUBLE UNSIGNED NULL,
  `Area_Sigla` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Curso_Area1_idx` (`Area_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Area1`
    FOREIGN KEY (`Area_Sigla`)
    REFERENCES `PUCMinas`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PUCMinas`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUCMinas`.`Modulo` (
  `Sigla` VARCHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Curso_Sigla` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Modulo_Curso1_idx` (`Curso_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_Curso1`
    FOREIGN KEY (`Curso_Sigla`)
    REFERENCES `PUCMinas`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PUCMinas`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUCMinas`.`Aluno` (
  `CPF` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `DataNasc` DATE NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PUCMinas`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUCMinas`.`Matricula` (
  `Curso_Sigla` VARCHAR(3) NOT NULL,
  `Aluno_CPF` VARCHAR(11) NOT NULL,
  `Data` DATE NULL,
  `Pago` TINYINT NULL,
  INDEX `fk_Matricula_Curso_idx` (`Curso_Sigla` ASC) VISIBLE,
  INDEX `fk_Matricula_Aluno1_idx` (`Aluno_CPF` ASC) VISIBLE,
  PRIMARY KEY (`Curso_Sigla`, `Aluno_CPF`),
  CONSTRAINT `fk_Matricula_Curso`
    FOREIGN KEY (`Curso_Sigla`)
    REFERENCES `PUCMinas`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno_CPF`)
    REFERENCES `PUCMinas`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PUCMinas`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUCMinas`.`Professor` (
  `CPF` VARCHAR(11) NOT NULL,
  `Curso_Sigla` VARCHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`, `Curso_Sigla`),
  INDEX `fk_Professor_Curso1_idx` (`Curso_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`Curso_Sigla`)
    REFERENCES `PUCMinas`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PUCMinas`.`Topico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUCMinas`.`Topico` (
  `Modulo_Sigla` VARCHAR(3) NOT NULL,
  `Sigla` VARCHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Horas` INT UNSIGNED NULL,
  PRIMARY KEY (`Modulo_Sigla`, `Sigla`),
  INDEX `fk_Topico_Modulo1_idx` (`Modulo_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Topico_Modulo1`
    FOREIGN KEY (`Modulo_Sigla`)
    REFERENCES `PUCMinas`.`Modulo` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
